[project]
name = "rietveld-refinement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "manuhergo", email = "manuhergo05@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "black>=26.5.1",
]

[project.scripts]
rietveld-refinement = "rietveld_refinement:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
